@echo off
set "AGENT_PROTOCOL=acp"
set "ACP_COMMAND=node"
set "ACP_ARGS=%~dp0bridge\src\index.mjs"
set "ACP_LABEL=DSH Web"
set "ACP_WORKSPACE=%CD%"
set "DSH_WEB_URL=http://127.0.0.1:3080"
set "QWEN_AUDIO_AGENT_ALLOWED_ORIGINS=http://127.0.0.1:3080"
set "QWEN_AUDIO_AGENT_TASK_MAX_CONCURRENT=8"
set "QWEN_AUDIO_AGENT_TASK_MAX_CONCURRENT_PER_OWNER=4"
set "QWEN_AUDIO_AGENT_ANNOUNCEMENT_BATCH_MS=0"
set "QWEN_AUDIO_AGENT_ANNOUNCEMENT_MAX_BATCH_ITEMS=1"
call "%~dp0node_modules\.bin\qwenaudio.cmd" %*
